### ISSUE TITLE
What is GetXmlStringFromXmlDoc?

### ISSUE THREAD

**Issue by murrayju** [DrakeES/jsxml#6]
The code is looking for this function, but it doesn't seem to be defined anywhere. When would this actually be used?

**Comment by murrayju** [comment]
Similarly, there is an `htmlentities()` function used that also is not defined.

**Comment by DrakeES** [comment]
Thank for your findings, murrayju. Those functions would have been defined in earlier versions of the library, but perhaps become redundant in its present shape. I have not been maintaining the library for quite a while — you may see the last commits were made by other contributors. If you want to make the library better I can add you to the contributors.

**Comment by DrakeES** [comment]
Thank you cybermerlin!

**Comment by cybermerlin** [comment]
no problem
